"""Add savaitgalis field

Revision ID: 63cfdcc6b85d
Revises: 
Create Date: 2024-10-08 12:35:46.814373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cfdcc6b85d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savaitgalis', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiration')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiration', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('ride_result', schema=None) as batch_op:
        batch_op.drop_column('savaitgalis')

    # ### end Alembic commands ###
