"""Update database schema

Revision ID: bade11e53001
Revises: cb711367cc59
Create Date: 2024-10-14 08:37:42.364749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bade11e53001'
down_revision = 'cb711367cc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pavadinimas', sa.VARCHAR(length=100), nullable=False),
    sa.Column('adresas', sa.VARCHAR(length=200), nullable=False),
    sa.Column('apskritis', sa.VARCHAR(length=50), nullable=False),
    sa.Column('darbo_laikas', sa.VARCHAR(length=100), nullable=True),
    sa.Column('darbuotoju_darbo_laikas', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sestadienio_darbo_laikas', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sekmadienio_darbo_laikas', sa.VARCHAR(length=100), nullable=True),
    sa.Column('google_maps_nuoroda', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
