"""Add Store table

Revision ID: c013e9214462
Revises: bade11e53001
Create Date: 2024-10-14 15:10:44.083394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c013e9214462'
down_revision = 'bade11e53001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pavadinimas', sa.String(length=100), nullable=False),
    sa.Column('adresas', sa.String(length=200), nullable=False),
    sa.Column('apskritis', sa.String(length=50), nullable=False),
    sa.Column('darbo_laikas', sa.String(length=100), nullable=True),
    sa.Column('darbuotoju_darbo_laikas', sa.String(length=100), nullable=True),
    sa.Column('sestadienio_darbo_laikas', sa.String(length=100), nullable=True),
    sa.Column('sekmadienio_darbo_laikas', sa.String(length=100), nullable=True),
    sa.Column('google_maps_nuoroda', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    # ### end Alembic commands ###
