"""Initial migration

Revision ID: cb711367cc59
Revises: 
Create Date: 2024-10-11 11:36:13.339741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb711367cc59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ride_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('auto_nr', sa.String(length=20), nullable=False),
    sa.Column('tasku_kiekis', sa.Float(), nullable=False),
    sa.Column('km_kiekis', sa.Float(), nullable=False),
    sa.Column('pakrautos_paletes', sa.Float(), nullable=False),
    sa.Column('tara', sa.Float(), nullable=False),
    sa.Column('atgalines_paletes', sa.Float(), nullable=False),
    sa.Column('eur_uz_reisa', sa.Float(), nullable=False),
    sa.Column('menesis', sa.String(length=7), nullable=False),
    sa.Column('savaitgalis', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ride_result')
    op.drop_table('user')
    # ### end Alembic commands ###
